# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nombre_plan: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param nombre_plan: The nombre_plan of this InlineResponse2001.  # noqa: E501
        :type nombre_plan: str
        """
        self.swagger_types = {
            'nombre_plan': str
        }

        self.attribute_map = {
            'nombre_plan': 'nombre_plan'
        }
        self._nombre_plan = nombre_plan

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nombre_plan(self) -> str:
        """Gets the nombre_plan of this InlineResponse2001.

        Nombre del plan de suscripción  # noqa: E501

        :return: The nombre_plan of this InlineResponse2001.
        :rtype: str
        """
        return self._nombre_plan

    @nombre_plan.setter
    def nombre_plan(self, nombre_plan: str):
        """Sets the nombre_plan of this InlineResponse2001.

        Nombre del plan de suscripción  # noqa: E501

        :param nombre_plan: The nombre_plan of this InlineResponse2001.
        :type nombre_plan: str
        """

        self._nombre_plan = nombre_plan
