# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Perfil(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, id_usuario: int=None, apodo: str=None, imagen_avatar: str=None):  # noqa: E501
        """Perfil - a model defined in Swagger

        :param id: The id of this Perfil.  # noqa: E501
        :type id: int
        :param id_usuario: The id_usuario of this Perfil.  # noqa: E501
        :type id_usuario: int
        :param apodo: The apodo of this Perfil.  # noqa: E501
        :type apodo: str
        :param imagen_avatar: The imagen_avatar of this Perfil.  # noqa: E501
        :type imagen_avatar: str
        """
        self.swagger_types = {
            'id': int,
            'id_usuario': int,
            'apodo': str,
            'imagen_avatar': str
        }

        self.attribute_map = {
            'id': 'id',
            'id_usuario': 'id_usuario',
            'apodo': 'apodo',
            'imagen_avatar': 'imagen_avatar'
        }
        self._id = id
        self._id_usuario = id_usuario
        self._apodo = apodo
        self._imagen_avatar = imagen_avatar

    @classmethod
    def from_dict(cls, dikt) -> 'Perfil':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Perfil of this Perfil.  # noqa: E501
        :rtype: Perfil
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Perfil.


        :return: The id of this Perfil.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Perfil.


        :param id: The id of this Perfil.
        :type id: int
        """

        self._id = id

    @property
    def id_usuario(self) -> int:
        """Gets the id_usuario of this Perfil.


        :return: The id_usuario of this Perfil.
        :rtype: int
        """
        return self._id_usuario

    @id_usuario.setter
    def id_usuario(self, id_usuario: int):
        """Sets the id_usuario of this Perfil.


        :param id_usuario: The id_usuario of this Perfil.
        :type id_usuario: int
        """

        self._id_usuario = id_usuario

    @property
    def apodo(self) -> str:
        """Gets the apodo of this Perfil.


        :return: The apodo of this Perfil.
        :rtype: str
        """
        return self._apodo

    @apodo.setter
    def apodo(self, apodo: str):
        """Sets the apodo of this Perfil.


        :param apodo: The apodo of this Perfil.
        :type apodo: str
        """

        self._apodo = apodo

    @property
    def imagen_avatar(self) -> str:
        """Gets the imagen_avatar of this Perfil.


        :return: The imagen_avatar of this Perfil.
        :rtype: str
        """
        return self._imagen_avatar

    @imagen_avatar.setter
    def imagen_avatar(self, imagen_avatar: str):
        """Sets the imagen_avatar of this Perfil.


        :param imagen_avatar: The imagen_avatar of this Perfil.
        :type imagen_avatar: str
        """

        self._imagen_avatar = imagen_avatar
