# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Plan(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_plan: int=None, nombre_plan: str=None, precio: float=None, descripcion: str=None):  # noqa: E501
        """Plan - a model defined in Swagger

        :param id_plan: The id_plan of this Plan.  # noqa: E501
        :type id_plan: int
        :param nombre_plan: The nombre_plan of this Plan.  # noqa: E501
        :type nombre_plan: str
        :param precio: The precio of this Plan.  # noqa: E501
        :type precio: float
        :param descripcion: The descripcion of this Plan.  # noqa: E501
        :type descripcion: str
        """
        self.swagger_types = {
            'id_plan': int,
            'nombre_plan': str,
            'precio': float,
            'descripcion': str
        }

        self.attribute_map = {
            'id_plan': 'id_plan',
            'nombre_plan': 'nombre_plan',
            'precio': 'precio',
            'descripcion': 'descripcion'
        }
        self._id_plan = id_plan
        self._nombre_plan = nombre_plan
        self._precio = precio
        self._descripcion = descripcion

    @classmethod
    def from_dict(cls, dikt) -> 'Plan':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Plan of this Plan.  # noqa: E501
        :rtype: Plan
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_plan(self) -> int:
        """Gets the id_plan of this Plan.


        :return: The id_plan of this Plan.
        :rtype: int
        """
        return self._id_plan

    @id_plan.setter
    def id_plan(self, id_plan: int):
        """Sets the id_plan of this Plan.


        :param id_plan: The id_plan of this Plan.
        :type id_plan: int
        """

        self._id_plan = id_plan

    @property
    def nombre_plan(self) -> str:
        """Gets the nombre_plan of this Plan.


        :return: The nombre_plan of this Plan.
        :rtype: str
        """
        return self._nombre_plan

    @nombre_plan.setter
    def nombre_plan(self, nombre_plan: str):
        """Sets the nombre_plan of this Plan.


        :param nombre_plan: The nombre_plan of this Plan.
        :type nombre_plan: str
        """

        self._nombre_plan = nombre_plan

    @property
    def precio(self) -> float:
        """Gets the precio of this Plan.


        :return: The precio of this Plan.
        :rtype: float
        """
        return self._precio

    @precio.setter
    def precio(self, precio: float):
        """Sets the precio of this Plan.


        :param precio: The precio of this Plan.
        :type precio: float
        """

        self._precio = precio

    @property
    def descripcion(self) -> str:
        """Gets the descripcion of this Plan.


        :return: The descripcion of this Plan.
        :rtype: str
        """
        return self._descripcion

    @descripcion.setter
    def descripcion(self, descripcion: str):
        """Sets the descripcion of this Plan.


        :param descripcion: The descripcion of this Plan.
        :type descripcion: str
        """

        self._descripcion = descripcion
